//
// server.cpp
// ~~~~~~~~~~
//
// Copyright (c) 2003-2010 Christopher M. Kohlhoff (chris at kohlhoff dot com)
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//


#include "server.h"
#include "utils.h"
#include <iostream>
#include "optionmanager.h"
#include "optionreader.h"
#include <ctime>

class StreamReader : public OptionReader
{
public:
    StreamReader& operator<<(const std::string& text)
    {
        if (key.empty())
        {
            key = text;
        }
        else
        {
            m_values[key] = text;
            key.clear();
        }
        return *this;
    }
    void readOptions()
    {

    }

private:
    std::string key;
};


int main()
{

    OptionManager options;

    std::string dummy;

    StreamReader* stream1 = new StreamReader();
    options.addReader(stream1);
    *stream1 << "coucou" << "caca" << "coucou1" << "caca" << "coucou2" << "caca" << "coucou3" << "caca" << "coucou4" << "caca" << "coucou5" << "caca" << "coucou6" << "caca" << "coucou7" << "caca" << "coucou8" << "caca" << "coucou9" << "caca" << "coucou10" << "caca" << "coucou11" << "caca" << "coucou12" << "caca" << "coucou13" << "caca" << "coucou14" << "caca" << "coucou15" << "caca" << "coucou16" << "caca" << "coucou17" << "caca" << "coucou18" << "caca" << "coucou19" << "caca" << "coucou20" << "caca" << "coucou21" << "caca" << "coucou22" << "caca" << "coucou23" << "caca" << "coucou24" << "caca" << "coucou25" << "caca" << "coucou26" << "caca" << "coucou27" << "caca" << "coucou28" << "caca" << "coucou29" << "caca" << "coucou30" << "caca" << "coucou31" << "caca" << "coucou32" << "caca" << "coucou33" << "caca" << "coucou34" << "caca" << "coucou35" << "caca" << "coucou36" << "caca" << "coucou37" << "caca" << "coucou38" << "caca" << "coucou39" << "caca" << "coucou40" << "caca" << "coucou41" << "caca" << "coucou42" << "caca" << "coucou43" << "caca" << "coucou44" << "caca";
    options.addOption("coucou", dummy).addOption("coucou1", dummy).addOption("coucou2", dummy).addOption("coucou3", dummy).addOption("coucou4", dummy).addOption("coucou5", dummy).addOption("coucou6", dummy).addOption("coucou7", dummy).addOption("coucou8", dummy).addOption("coucou9", dummy).addOption("coucou10", dummy).addOption("coucou11", dummy).addOption("coucou12", dummy).addOption("coucou13", dummy).addOption("coucou14", dummy).addOption("coucou15", dummy).addOption("coucou16", dummy).addOption("coucou17", dummy).addOption("coucou18", dummy).addOption("coucou19", dummy).addOption("coucou20", dummy).addOption("coucou21", dummy).addOption("coucou22", dummy).addOption("coucou23", dummy).addOption("coucou24", dummy).addOption("coucou25", dummy).addOption("coucou26", dummy).addOption("coucou27", dummy).addOption("coucou28", dummy).addOption("coucou29", dummy).addOption("coucou30", dummy).addOption("coucou31", dummy).addOption("coucou32", dummy).addOption("coucou33", dummy).addOption("coucou34", dummy).addOption("coucou35", dummy).addOption("coucou36", dummy).addOption("coucou37", dummy).addOption("coucou38", dummy).addOption("coucou39", dummy).addOption("coucou40", dummy).addOption("coucou41", dummy).addOption("coucou42", dummy).addOption("coucou43", dummy).addOption("coucou44", dummy);

    StreamReader* stream2 = new StreamReader();
    options.addReader(stream2);
    *stream2 << "pedale" << "caca" << "pedale1" << "caca" << "pedale2" << "caca" << "pedale3" << "caca" << "pedale4" << "caca" << "pedale5" << "caca" << "pedale6" << "caca" << "pedale7" << "caca" << "pedale8" << "caca" << "pedale9" << "caca" << "pedale10" << "caca" << "pedale11" << "caca" << "pedale12" << "caca" << "pedale13" << "caca" << "pedale14" << "caca" << "pedale15" << "caca" << "pedale16" << "caca" << "pedale17" << "caca" << "pedale18" << "caca" << "pedale19" << "caca" << "pedale20" << "caca" << "pedale21" << "caca" << "pedale22" << "caca" << "pedale23" << "caca" << "pedale24" << "caca" << "pedale25" << "caca" << "pedale26" << "caca" << "pedale27" << "caca" << "pedale28" << "caca" << "pedale29" << "caca" << "pedale30" << "caca" << "pedale31" << "caca" << "pedale32" << "caca" << "pedale33" << "caca" << "pedale34" << "caca" << "pedale35" << "caca" << "pedale36" << "caca" << "pedale37" << "caca" << "pedale38" << "caca" << "pedale39" << "caca" << "pedale40" << "caca" << "pedale41" << "caca" << "pedale42" << "caca" << "pedale43" << "caca" << "pedale44" << "caca";
    options.addOption("pedale", dummy).addOption("pedale1", dummy).addOption("pedale2", dummy).addOption("pedale3", dummy).addOption("pedale4", dummy).addOption("pedale5", dummy).addOption("pedale6", dummy).addOption("pedale7", dummy).addOption("pedale8", dummy).addOption("pedale9", dummy).addOption("pedale10", dummy).addOption("pedale11", dummy).addOption("pedale12", dummy).addOption("pedale13", dummy).addOption("pedale14", dummy).addOption("pedale15", dummy).addOption("pedale16", dummy).addOption("pedale17", dummy).addOption("pedale18", dummy).addOption("pedale19", dummy).addOption("pedale20", dummy).addOption("pedale21", dummy).addOption("pedale22", dummy).addOption("pedale23", dummy).addOption("pedale24", dummy).addOption("pedale25", dummy).addOption("pedale26", dummy).addOption("pedale27", dummy).addOption("pedale28", dummy).addOption("pedale29", dummy).addOption("pedale30", dummy).addOption("pedale31", dummy).addOption("pedale32", dummy).addOption("pedale33", dummy).addOption("pedale34", dummy).addOption("pedale35", dummy).addOption("pedale36", dummy).addOption("pedale37", dummy).addOption("pedale38", dummy).addOption("pedale39", dummy).addOption("pedale40", dummy).addOption("pedale41", dummy).addOption("pedale42", dummy).addOption("pedale43", dummy).addOption("pedale44", dummy);

    StreamReader* stream3 = new StreamReader();
    options.addReader(stream3);
    *stream3 << "salut" << "caca" << "salut1" << "caca" << "salut2" << "caca" << "salut3" << "caca" << "salut4" << "caca" << "salut5" << "caca" << "salut6" << "caca" << "salut7" << "caca" << "salut8" << "caca" << "salut9" << "caca" << "salut10" << "caca" << "salut11" << "caca" << "salut12" << "caca" << "salut13" << "caca" << "salut14" << "caca" << "salut15" << "caca" << "salut16" << "caca" << "salut17" << "caca" << "salut18" << "caca" << "salut19" << "caca" << "salut20" << "caca" << "salut21" << "caca" << "salut22" << "caca" << "salut23" << "caca" << "salut24" << "caca" << "salut25" << "caca" << "salut26" << "caca" << "salut27" << "caca" << "salut28" << "caca" << "salut29" << "caca" << "salut30" << "caca" << "salut31" << "caca" << "salut32" << "caca" << "salut33" << "caca" << "salut34" << "caca" << "salut35" << "caca" << "salut36" << "caca" << "salut37" << "caca" << "salut38" << "caca" << "salut39" << "caca" << "salut40" << "caca" << "salut41" << "caca" << "salut42" << "caca" << "salut43" << "caca" << "salut44" << "caca";
    options.addOption("salut", dummy).addOption("salut1", dummy).addOption("salut2", dummy).addOption("salut3", dummy).addOption("salut4", dummy).addOption("salut5", dummy).addOption("salut6", dummy).addOption("salut7", dummy).addOption("salut8", dummy).addOption("salut9", dummy).addOption("salut10", dummy).addOption("salut11", dummy).addOption("salut12", dummy).addOption("salut13", dummy).addOption("salut14", dummy).addOption("salut15", dummy).addOption("salut16", dummy).addOption("salut17", dummy).addOption("salut18", dummy).addOption("salut19", dummy).addOption("salut20", dummy).addOption("salut21", dummy).addOption("salut22", dummy).addOption("salut23", dummy).addOption("salut24", dummy).addOption("salut25", dummy).addOption("salut26", dummy).addOption("salut27", dummy).addOption("salut28", dummy).addOption("salut29", dummy).addOption("salut30", dummy).addOption("salut31", dummy).addOption("salut32", dummy).addOption("salut33", dummy).addOption("salut34", dummy).addOption("salut35", dummy).addOption("salut36", dummy).addOption("salut37", dummy).addOption("salut38", dummy).addOption("salut39", dummy).addOption("salut40", dummy).addOption("salut41", dummy).addOption("salut42", dummy).addOption("salut43", dummy).addOption("salut44", dummy);

    StreamReader* stream4 = new StreamReader();
    options.addReader(stream4);
    *stream4 << "salope" << "caca" << "salope1" << "caca" << "salope2" << "caca" << "salope3" << "caca" << "salope4" << "caca" << "salope5" << "caca" << "salope6" << "caca" << "salope7" << "caca" << "salope8" << "caca" << "salope9" << "caca" << "salope10" << "caca" << "salope11" << "caca" << "salope12" << "caca" << "salope13" << "caca" << "salope14" << "caca" << "salope15" << "caca" << "salope16" << "caca" << "salope17" << "caca" << "salope18" << "caca" << "salope19" << "caca" << "salope20" << "caca" << "salope21" << "caca" << "salope22" << "caca" << "salope23" << "caca" << "salope24" << "caca" << "salope25" << "caca" << "salope26" << "caca" << "salope27" << "caca" << "salope28" << "caca" << "salope29" << "caca" << "salope30" << "caca" << "salope31" << "caca" << "salope32" << "caca" << "salope33" << "caca" << "salope34" << "caca" << "salope35" << "caca" << "salope36" << "caca" << "salope37" << "caca" << "salope38" << "caca" << "salope39" << "caca" << "salope40" << "caca" << "salope41" << "caca" << "salope42" << "caca" << "salope43" << "caca" << "salope44" << "caca";
    options.addOption("salope", dummy).addOption("salope1", dummy).addOption("salope2", dummy).addOption("salope3", dummy).addOption("salope4", dummy).addOption("salope5", dummy).addOption("salope6", dummy).addOption("salope7", dummy).addOption("salope8", dummy).addOption("salope9", dummy).addOption("salope10", dummy).addOption("salope11", dummy).addOption("salope12", dummy).addOption("salope13", dummy).addOption("salope14", dummy).addOption("salope15", dummy).addOption("salope16", dummy).addOption("salope17", dummy).addOption("salope18", dummy).addOption("salope19", dummy).addOption("salope20", dummy).addOption("salope21", dummy).addOption("salope22", dummy).addOption("salope23", dummy).addOption("salope24", dummy).addOption("salope25", dummy).addOption("salope26", dummy).addOption("salope27", dummy).addOption("salope28", dummy).addOption("salope29", dummy).addOption("salope30", dummy).addOption("salope31", dummy).addOption("salope32", dummy).addOption("salope33", dummy).addOption("salope34", dummy).addOption("salope35", dummy).addOption("salope36", dummy).addOption("salope37", dummy).addOption("salope38", dummy).addOption("salope39", dummy).addOption("salope40", dummy).addOption("salope41", dummy).addOption("salope42", dummy).addOption("salope43", dummy).addOption("salope44", dummy);

    StreamReader* stream5 = new StreamReader();
    options.addReader(stream5);
    *stream5 << "catin" << "caca" << "catin1" << "caca" << "catin2" << "caca" << "catin3" << "caca" << "catin4" << "caca" << "catin5" << "caca" << "catin6" << "caca" << "catin7" << "caca" << "catin8" << "caca" << "catin9" << "caca" << "catin10" << "caca" << "catin11" << "caca" << "catin12" << "caca" << "catin13" << "caca" << "catin14" << "caca" << "catin15" << "caca" << "catin16" << "caca" << "catin17" << "caca" << "catin18" << "caca" << "catin19" << "caca" << "catin20" << "caca" << "catin21" << "caca" << "catin22" << "caca" << "catin23" << "caca" << "catin24" << "caca" << "catin25" << "caca" << "catin26" << "caca" << "catin27" << "caca" << "catin28" << "caca" << "catin29" << "caca" << "catin30" << "caca" << "catin31" << "caca" << "catin32" << "caca" << "catin33" << "caca" << "catin34" << "caca" << "catin35" << "caca" << "catin36" << "caca" << "catin37" << "caca" << "catin38" << "caca" << "catin39" << "caca" << "catin40" << "caca" << "catin41" << "caca" << "catin42" << "caca" << "catin43" << "caca" << "catin44" << "caca";
    options.addOption("catin", dummy).addOption("catin1", dummy).addOption("catin2", dummy).addOption("catin3", dummy).addOption("catin4", dummy).addOption("catin5", dummy).addOption("catin6", dummy).addOption("catin7", dummy).addOption("catin8", dummy).addOption("catin9", dummy).addOption("catin10", dummy).addOption("catin11", dummy).addOption("catin12", dummy).addOption("catin13", dummy).addOption("catin14", dummy).addOption("catin15", dummy).addOption("catin16", dummy).addOption("catin17", dummy).addOption("catin18", dummy).addOption("catin19", dummy).addOption("catin20", dummy).addOption("catin21", dummy).addOption("catin22", dummy).addOption("catin23", dummy).addOption("catin24", dummy).addOption("catin25", dummy).addOption("catin26", dummy).addOption("catin27", dummy).addOption("catin28", dummy).addOption("catin29", dummy).addOption("catin30", dummy).addOption("catin31", dummy).addOption("catin32", dummy).addOption("catin33", dummy).addOption("catin34", dummy).addOption("catin35", dummy).addOption("catin36", dummy).addOption("catin37", dummy).addOption("catin38", dummy).addOption("catin39", dummy).addOption("catin40", dummy).addOption("catin41", dummy).addOption("catin42", dummy).addOption("catin43", dummy).addOption("catin44", dummy);

    StreamReader* stream6 = new StreamReader();
    options.addReader(stream6);
    *stream6 << "choufleur" << "caca" << "choufleur1" << "caca" << "choufleur2" << "caca" << "choufleur3" << "caca" << "choufleur4" << "caca" << "choufleur5" << "caca" << "choufleur6" << "caca" << "choufleur7" << "caca" << "choufleur8" << "caca" << "choufleur9" << "caca" << "choufleur10" << "caca" << "choufleur11" << "caca" << "choufleur12" << "caca" << "choufleur13" << "caca" << "choufleur14" << "caca" << "choufleur15" << "caca" << "choufleur16" << "caca" << "choufleur17" << "caca" << "choufleur18" << "caca" << "choufleur19" << "caca" << "choufleur20" << "caca" << "choufleur21" << "caca" << "choufleur22" << "caca" << "choufleur23" << "caca" << "choufleur24" << "caca" << "choufleur25" << "caca" << "choufleur26" << "caca" << "choufleur27" << "caca" << "choufleur28" << "caca" << "choufleur29" << "caca" << "choufleur30" << "caca" << "choufleur31" << "caca" << "choufleur32" << "caca" << "choufleur33" << "caca" << "choufleur34" << "caca" << "choufleur35" << "caca" << "choufleur36" << "caca" << "choufleur37" << "caca" << "choufleur38" << "caca" << "choufleur39" << "caca" << "choufleur40" << "caca" << "choufleur41" << "caca" << "choufleur42" << "caca" << "choufleur43" << "caca" << "choufleur44" << "caca";
    options.addOption("choufleur", dummy).addOption("choufleur1", dummy).addOption("choufleur2", dummy).addOption("choufleur3", dummy).addOption("choufleur4", dummy).addOption("choufleur5", dummy).addOption("choufleur6", dummy).addOption("choufleur7", dummy).addOption("choufleur8", dummy).addOption("choufleur9", dummy).addOption("choufleur10", dummy).addOption("choufleur11", dummy).addOption("choufleur12", dummy).addOption("choufleur13", dummy).addOption("choufleur14", dummy).addOption("choufleur15", dummy).addOption("choufleur16", dummy).addOption("choufleur17", dummy).addOption("choufleur18", dummy).addOption("choufleur19", dummy).addOption("choufleur20", dummy).addOption("choufleur21", dummy).addOption("choufleur22", dummy).addOption("choufleur23", dummy).addOption("choufleur24", dummy).addOption("choufleur25", dummy).addOption("choufleur26", dummy).addOption("choufleur27", dummy).addOption("choufleur28", dummy).addOption("choufleur29", dummy).addOption("choufleur30", dummy).addOption("choufleur31", dummy).addOption("choufleur32", dummy).addOption("choufleur33", dummy).addOption("choufleur34", dummy).addOption("choufleur35", dummy).addOption("choufleur36", dummy).addOption("choufleur37", dummy).addOption("choufleur38", dummy).addOption("choufleur39", dummy).addOption("choufleur40", dummy).addOption("choufleur41", dummy).addOption("choufleur42", dummy).addOption("choufleur43", dummy).addOption("choufleur44", dummy);

    StreamReader* stream7 = new StreamReader();
    options.addReader(stream7);
    *stream7 << "chien" << "caca" << "chien1" << "caca" << "chien2" << "caca" << "chien3" << "caca" << "chien4" << "caca" << "chien5" << "caca" << "chien6" << "caca" << "chien7" << "caca" << "chien8" << "caca" << "chien9" << "caca" << "chien10" << "caca" << "chien11" << "caca" << "chien12" << "caca" << "chien13" << "caca" << "chien14" << "caca" << "chien15" << "caca" << "chien16" << "caca" << "chien17" << "caca" << "chien18" << "caca" << "chien19" << "caca" << "chien20" << "caca" << "chien21" << "caca" << "chien22" << "caca" << "chien23" << "caca" << "chien24" << "caca" << "chien25" << "caca" << "chien26" << "caca" << "chien27" << "caca" << "chien28" << "caca" << "chien29" << "caca" << "chien30" << "caca" << "chien31" << "caca" << "chien32" << "caca" << "chien33" << "caca" << "chien34" << "caca" << "chien35" << "caca" << "chien36" << "caca" << "chien37" << "caca" << "chien38" << "caca" << "chien39" << "caca" << "chien40" << "caca" << "chien41" << "caca" << "chien42" << "caca" << "chien43" << "caca" << "chien44" << "caca";
    options.addOption("chien", dummy).addOption("chien1", dummy).addOption("chien2", dummy).addOption("chien3", dummy).addOption("chien4", dummy).addOption("chien5", dummy).addOption("chien6", dummy).addOption("chien7", dummy).addOption("chien8", dummy).addOption("chien9", dummy).addOption("chien10", dummy).addOption("chien11", dummy).addOption("chien12", dummy).addOption("chien13", dummy).addOption("chien14", dummy).addOption("chien15", dummy).addOption("chien16", dummy).addOption("chien17", dummy).addOption("chien18", dummy).addOption("chien19", dummy).addOption("chien20", dummy).addOption("chien21", dummy).addOption("chien22", dummy).addOption("chien23", dummy).addOption("chien24", dummy).addOption("chien25", dummy).addOption("chien26", dummy).addOption("chien27", dummy).addOption("chien28", dummy).addOption("chien29", dummy).addOption("chien30", dummy).addOption("chien31", dummy).addOption("chien32", dummy).addOption("chien33", dummy).addOption("chien34", dummy).addOption("chien35", dummy).addOption("chien36", dummy).addOption("chien37", dummy).addOption("chien38", dummy).addOption("chien39", dummy).addOption("chien40", dummy).addOption("chien41", dummy).addOption("chien42", dummy).addOption("chien43", dummy).addOption("chien44", dummy);


    StreamReader* stream8 = new StreamReader();
    options.addReader(stream8);
    *stream8 << "musique" << "caca" << "musique1" << "caca" << "musique2" << "caca" << "musique3" << "caca" << "musique4" << "caca" << "musique5" << "caca" << "musique6" << "caca" << "musique7" << "caca" << "musique8" << "caca" << "musique9" << "caca" << "musique10" << "caca" << "musique11" << "caca" << "musique12" << "caca" << "musique13" << "caca" << "musique14" << "caca" << "musique15" << "caca" << "musique16" << "caca" << "musique17" << "caca" << "musique18" << "caca" << "musique19" << "caca" << "musique20" << "caca" << "musique21" << "caca" << "musique22" << "caca" << "musique23" << "caca" << "musique24" << "caca" << "musique25" << "caca" << "musique26" << "caca" << "musique27" << "caca" << "musique28" << "caca" << "musique29" << "caca" << "musique30" << "caca" << "musique31" << "caca" << "musique32" << "caca" << "musique33" << "caca" << "musique34" << "caca" << "musique35" << "caca" << "musique36" << "caca" << "musique37" << "caca" << "musique38" << "caca" << "musique39" << "caca" << "musique40" << "caca" << "musique41" << "caca" << "musique42" << "caca" << "musique43" << "caca" << "musique44" << "caca";
    options.addOption("musique", dummy).addOption("musique1", dummy).addOption("musique2", dummy).addOption("musique3", dummy).addOption("musique4", dummy).addOption("musique5", dummy).addOption("musique6", dummy).addOption("musique7", dummy).addOption("musique8", dummy).addOption("musique9", dummy).addOption("musique10", dummy).addOption("musique11", dummy).addOption("musique12", dummy).addOption("musique13", dummy).addOption("musique14", dummy).addOption("musique15", dummy).addOption("musique16", dummy).addOption("musique17", dummy).addOption("musique18", dummy).addOption("musique19", dummy).addOption("musique20", dummy).addOption("musique21", dummy).addOption("musique22", dummy).addOption("musique23", dummy).addOption("musique24", dummy).addOption("musique25", dummy).addOption("musique26", dummy).addOption("musique27", dummy).addOption("musique28", dummy).addOption("musique29", dummy).addOption("musique30", dummy).addOption("musique31", dummy).addOption("musique32", dummy).addOption("musique33", dummy).addOption("musique34", dummy).addOption("musique35", dummy).addOption("musique36", dummy).addOption("musique37", dummy).addOption("musique38", dummy).addOption("musique39", dummy).addOption("musique40", dummy).addOption("musique41", dummy).addOption("musique42", dummy).addOption("musique43", dummy).addOption("musique44", dummy);

	StreamReader* stream9 = new StreamReader();
    options.addReader(stream9);
    *stream9 << "smile" << "caca" << "smile1" << "caca" << "smile2" << "caca" << "smile3" << "caca" << "smile4" << "caca" << "smile5" << "caca" << "smile6" << "caca" << "smile7" << "caca" << "smile8" << "caca" << "smile9" << "caca" << "smile10" << "caca" << "smile11" << "caca" << "smile12" << "caca" << "smile13" << "caca" << "smile14" << "caca" << "smile15" << "caca" << "smile16" << "caca" << "smile17" << "caca" << "smile18" << "caca" << "smile19" << "caca" << "smile20" << "caca" << "smile21" << "caca" << "smile22" << "caca" << "smile23" << "caca" << "smile24" << "caca" << "smile25" << "caca" << "smile26" << "caca" << "smile27" << "caca" << "smile28" << "caca" << "smile29" << "caca" << "smile30" << "caca" << "smile31" << "caca" << "smile32" << "caca" << "smile33" << "caca" << "smile34" << "caca" << "smile35" << "caca" << "smile36" << "caca" << "smile37" << "caca" << "smile38" << "caca" << "smile39" << "caca" << "smile40" << "caca" << "smile41" << "caca" << "smile42" << "caca" << "smile43" << "caca" << "smile44" << "caca";
    options.addOption("smile", dummy).addOption("smile1", dummy).addOption("smile2", dummy).addOption("smile3", dummy).addOption("smile4", dummy).addOption("smile5", dummy).addOption("smile6", dummy).addOption("smile7", dummy).addOption("smile8", dummy).addOption("smile9", dummy).addOption("smile10", dummy).addOption("smile11", dummy).addOption("smile12", dummy).addOption("smile13", dummy).addOption("smile14", dummy).addOption("smile15", dummy).addOption("smile16", dummy).addOption("smile17", dummy).addOption("smile18", dummy).addOption("smile19", dummy).addOption("smile20", dummy).addOption("smile21", dummy).addOption("smile22", dummy).addOption("smile23", dummy).addOption("smile24", dummy).addOption("smile25", dummy).addOption("smile26", dummy).addOption("smile27", dummy).addOption("smile28", dummy).addOption("smile29", dummy).addOption("smile30", dummy).addOption("smile31", dummy).addOption("smile32", dummy).addOption("smile33", dummy).addOption("smile34", dummy).addOption("smile35", dummy).addOption("smile36", dummy).addOption("smile37", dummy).addOption("smile38", dummy).addOption("smile39", dummy).addOption("smile40", dummy).addOption("smile41", dummy).addOption("smile42", dummy).addOption("smile43", dummy).addOption("smile44", dummy);

	StreamReader* stream10 = new StreamReader();
    options.addReader(stream10);
    *stream10 << "loe" << "caca" << "love1" << "caca" << "love2" << "caca" << "love3" << "caca" << "love4" << "caca" << "love5" << "caca" << "love6" << "caca" << "love7" << "caca" << "love8" << "caca" << "love9" << "caca" << "love10" << "caca" << "love11" << "caca" << "love12" << "caca" << "love13" << "caca" << "love14" << "caca" << "love15" << "caca" << "love16" << "caca" << "love17" << "caca" << "love18" << "caca" << "love19" << "caca" << "love20" << "caca" << "love21" << "caca" << "love22" << "caca" << "love23" << "caca" << "love24" << "caca" << "love25" << "caca" << "love26" << "caca" << "love27" << "caca" << "love28" << "caca" << "love29" << "caca" << "love30" << "caca" << "love31" << "caca" << "love32" << "caca" << "love33" << "caca" << "love34" << "caca" << "love35" << "caca" << "love36" << "caca" << "love37" << "caca" << "love38" << "caca" << "love39" << "caca" << "love40" << "caca" << "love41" << "caca" << "love42" << "caca" << "love43" << "caca" << "love44" << "caca";
    options.addOption("love", dummy).addOption("love1", dummy).addOption("love2", dummy).addOption("love3", dummy).addOption("love4", dummy).addOption("love5", dummy).addOption("love6", dummy).addOption("love7", dummy).addOption("love8", dummy).addOption("love9", dummy).addOption("love10", dummy).addOption("love11", dummy).addOption("love12", dummy).addOption("love13", dummy).addOption("love14", dummy).addOption("love15", dummy).addOption("love16", dummy).addOption("love17", dummy).addOption("love18", dummy).addOption("love19", dummy).addOption("love20", dummy).addOption("love21", dummy).addOption("love22", dummy).addOption("love23", dummy).addOption("love24", dummy).addOption("love25", dummy).addOption("love26", dummy).addOption("love27", dummy).addOption("love28", dummy).addOption("love29", dummy).addOption("love30", dummy).addOption("love31", dummy).addOption("love32", dummy).addOption("love33", dummy).addOption("love34", dummy).addOption("love35", dummy).addOption("love36", dummy).addOption("love37", dummy).addOption("love38", dummy).addOption("love39", dummy).addOption("love40", dummy).addOption("love41", dummy).addOption("love42", dummy).addOption("love43", dummy).addOption("love4", dummy);

    StreamReader* stream11 = new StreamReader();
    options.addReader(stream11);
    *stream11<< "coucou" << "caca" << "coucou1" << "caca" << "coucou2" << "caca" << "coucou3" << "caca" << "coucou4" << "caca" << "coucou5" << "caca" << "coucou6" << "caca" << "coucou7" << "caca" << "coucou8" << "caca" << "coucou9" << "caca" << "coucou10" << "caca" << "coucou11" << "caca" << "coucou12" << "caca" << "coucou13" << "caca" << "coucou14" << "caca" << "coucou15" << "caca" << "coucou16" << "caca" << "coucou17" << "caca" << "coucou18" << "caca" << "coucou19" << "caca" << "coucou20" << "caca" << "coucou21" << "caca" << "coucou22" << "caca" << "coucou23" << "caca" << "coucou24" << "caca" << "coucou25" << "caca" << "coucou26" << "caca" << "coucou27" << "caca" << "coucou28" << "caca" << "coucou29" << "caca" << "coucou30" << "caca" << "coucou31" << "caca" << "coucou32" << "caca" << "coucou33" << "caca" << "coucou34" << "caca" << "coucou35" << "caca" << "coucou36" << "caca" << "coucou37" << "caca" << "coucou38" << "caca" << "coucou39" << "caca" << "coucou40" << "caca" << "coucou41" << "caca" << "coucou42" << "caca" << "coucou43" << "caca" << "coucou44" << "caca";
    options.addOption("coucou", dummy).addOption("coucou1", dummy).addOption("coucou2", dummy).addOption("coucou3", dummy).addOption("coucou4", dummy).addOption("coucou5", dummy).addOption("coucou6", dummy).addOption("coucou7", dummy).addOption("coucou8", dummy).addOption("coucou9", dummy).addOption("coucou10", dummy).addOption("coucou11", dummy).addOption("coucou12", dummy).addOption("coucou13", dummy).addOption("coucou14", dummy).addOption("coucou15", dummy).addOption("coucou16", dummy).addOption("coucou17", dummy).addOption("coucou18", dummy).addOption("coucou19", dummy).addOption("coucou20", dummy).addOption("coucou21", dummy).addOption("coucou22", dummy).addOption("coucou23", dummy).addOption("coucou24", dummy).addOption("coucou25", dummy).addOption("coucou26", dummy).addOption("coucou27", dummy).addOption("coucou28", dummy).addOption("coucou29", dummy).addOption("coucou30", dummy).addOption("coucou31", dummy).addOption("coucou32", dummy).addOption("coucou33", dummy).addOption("coucou34", dummy).addOption("coucou35", dummy).addOption("coucou36", dummy).addOption("coucou37", dummy).addOption("coucou38", dummy).addOption("coucou39", dummy).addOption("coucou40", dummy).addOption("coucou41", dummy).addOption("coucou42", dummy).addOption("coucou43", dummy).addOption("coucou44", dummy);

    StreamReader* stream12 = new StreamReader();
    options.addReader(stream12);
    *stream12 << "pedale" << "caca" << "pedale1" << "caca" << "pedale2" << "caca" << "pedale3" << "caca" << "pedale4" << "caca" << "pedale5" << "caca" << "pedale6" << "caca" << "pedale7" << "caca" << "pedale8" << "caca" << "pedale9" << "caca" << "pedale10" << "caca" << "pedale11" << "caca" << "pedale12" << "caca" << "pedale13" << "caca" << "pedale14" << "caca" << "pedale15" << "caca" << "pedale16" << "caca" << "pedale17" << "caca" << "pedale18" << "caca" << "pedale19" << "caca" << "pedale20" << "caca" << "pedale21" << "caca" << "pedale22" << "caca" << "pedale23" << "caca" << "pedale24" << "caca" << "pedale25" << "caca" << "pedale26" << "caca" << "pedale27" << "caca" << "pedale28" << "caca" << "pedale29" << "caca" << "pedale30" << "caca" << "pedale31" << "caca" << "pedale32" << "caca" << "pedale33" << "caca" << "pedale34" << "caca" << "pedale35" << "caca" << "pedale36" << "caca" << "pedale37" << "caca" << "pedale38" << "caca" << "pedale39" << "caca" << "pedale40" << "caca" << "pedale41" << "caca" << "pedale42" << "caca" << "pedale43" << "caca" << "pedale44" << "caca";
    options.addOption("pedale", dummy).addOption("pedale1", dummy).addOption("pedale2", dummy).addOption("pedale3", dummy).addOption("pedale4", dummy).addOption("pedale5", dummy).addOption("pedale6", dummy).addOption("pedale7", dummy).addOption("pedale8", dummy).addOption("pedale9", dummy).addOption("pedale10", dummy).addOption("pedale11", dummy).addOption("pedale12", dummy).addOption("pedale13", dummy).addOption("pedale14", dummy).addOption("pedale15", dummy).addOption("pedale16", dummy).addOption("pedale17", dummy).addOption("pedale18", dummy).addOption("pedale19", dummy).addOption("pedale20", dummy).addOption("pedale21", dummy).addOption("pedale22", dummy).addOption("pedale23", dummy).addOption("pedale24", dummy).addOption("pedale25", dummy).addOption("pedale26", dummy).addOption("pedale27", dummy).addOption("pedale28", dummy).addOption("pedale29", dummy).addOption("pedale30", dummy).addOption("pedale31", dummy).addOption("pedale32", dummy).addOption("pedale33", dummy).addOption("pedale34", dummy).addOption("pedale35", dummy).addOption("pedale36", dummy).addOption("pedale37", dummy).addOption("pedale38", dummy).addOption("pedale39", dummy).addOption("pedale40", dummy).addOption("pedale41", dummy).addOption("pedale42", dummy).addOption("pedale43", dummy).addOption("pedale44", dummy);

    StreamReader* stream13 = new StreamReader();
    options.addReader(stream13);
    *stream13 << "salut" << "caca" << "salut1" << "caca" << "salut2" << "caca" << "salut3" << "caca" << "salut4" << "caca" << "salut5" << "caca" << "salut6" << "caca" << "salut7" << "caca" << "salut8" << "caca" << "salut9" << "caca" << "salut10" << "caca" << "salut11" << "caca" << "salut12" << "caca" << "salut13" << "caca" << "salut14" << "caca" << "salut15" << "caca" << "salut16" << "caca" << "salut17" << "caca" << "salut18" << "caca" << "salut19" << "caca" << "salut20" << "caca" << "salut21" << "caca" << "salut22" << "caca" << "salut23" << "caca" << "salut24" << "caca" << "salut25" << "caca" << "salut26" << "caca" << "salut27" << "caca" << "salut28" << "caca" << "salut29" << "caca" << "salut30" << "caca" << "salut31" << "caca" << "salut32" << "caca" << "salut33" << "caca" << "salut34" << "caca" << "salut35" << "caca" << "salut36" << "caca" << "salut37" << "caca" << "salut38" << "caca" << "salut39" << "caca" << "salut40" << "caca" << "salut41" << "caca" << "salut42" << "caca" << "salut43" << "caca" << "salut44" << "caca";
    options.addOption("salut", dummy).addOption("salut1", dummy).addOption("salut2", dummy).addOption("salut3", dummy).addOption("salut4", dummy).addOption("salut5", dummy).addOption("salut6", dummy).addOption("salut7", dummy).addOption("salut8", dummy).addOption("salut9", dummy).addOption("salut10", dummy).addOption("salut11", dummy).addOption("salut12", dummy).addOption("salut13", dummy).addOption("salut14", dummy).addOption("salut15", dummy).addOption("salut16", dummy).addOption("salut17", dummy).addOption("salut18", dummy).addOption("salut19", dummy).addOption("salut20", dummy).addOption("salut21", dummy).addOption("salut22", dummy).addOption("salut23", dummy).addOption("salut24", dummy).addOption("salut25", dummy).addOption("salut26", dummy).addOption("salut27", dummy).addOption("salut28", dummy).addOption("salut29", dummy).addOption("salut30", dummy).addOption("salut31", dummy).addOption("salut32", dummy).addOption("salut33", dummy).addOption("salut34", dummy).addOption("salut35", dummy).addOption("salut36", dummy).addOption("salut37", dummy).addOption("salut38", dummy).addOption("salut39", dummy).addOption("salut40", dummy).addOption("salut41", dummy).addOption("salut42", dummy).addOption("salut43", dummy).addOption("salut44", dummy);

    StreamReader* stream14 = new StreamReader();
    options.addReader(stream14);
    *stream14 << "salope" << "caca" << "salope1" << "caca" << "salope2" << "caca" << "salope3" << "caca" << "salope4" << "caca" << "salope5" << "caca" << "salope6" << "caca" << "salope7" << "caca" << "salope8" << "caca" << "salope9" << "caca" << "salope10" << "caca" << "salope11" << "caca" << "salope12" << "caca" << "salope13" << "caca" << "salope14" << "caca" << "salope15" << "caca" << "salope16" << "caca" << "salope17" << "caca" << "salope18" << "caca" << "salope19" << "caca" << "salope20" << "caca" << "salope21" << "caca" << "salope22" << "caca" << "salope23" << "caca" << "salope24" << "caca" << "salope25" << "caca" << "salope26" << "caca" << "salope27" << "caca" << "salope28" << "caca" << "salope29" << "caca" << "salope30" << "caca" << "salope31" << "caca" << "salope32" << "caca" << "salope33" << "caca" << "salope34" << "caca" << "salope35" << "caca" << "salope36" << "caca" << "salope37" << "caca" << "salope38" << "caca" << "salope39" << "caca" << "salope40" << "caca" << "salope41" << "caca" << "salope42" << "caca" << "salope43" << "caca" << "salope44" << "caca";
    options.addOption("salope", dummy).addOption("salope1", dummy).addOption("salope2", dummy).addOption("salope3", dummy).addOption("salope4", dummy).addOption("salope5", dummy).addOption("salope6", dummy).addOption("salope7", dummy).addOption("salope8", dummy).addOption("salope9", dummy).addOption("salope10", dummy).addOption("salope11", dummy).addOption("salope12", dummy).addOption("salope13", dummy).addOption("salope14", dummy).addOption("salope15", dummy).addOption("salope16", dummy).addOption("salope17", dummy).addOption("salope18", dummy).addOption("salope19", dummy).addOption("salope20", dummy).addOption("salope21", dummy).addOption("salope22", dummy).addOption("salope23", dummy).addOption("salope24", dummy).addOption("salope25", dummy).addOption("salope26", dummy).addOption("salope27", dummy).addOption("salope28", dummy).addOption("salope29", dummy).addOption("salope30", dummy).addOption("salope31", dummy).addOption("salope32", dummy).addOption("salope33", dummy).addOption("salope34", dummy).addOption("salope35", dummy).addOption("salope36", dummy).addOption("salope37", dummy).addOption("salope38", dummy).addOption("salope39", dummy).addOption("salope40", dummy).addOption("salope41", dummy).addOption("salope42", dummy).addOption("salope43", dummy).addOption("salope44", dummy);

    StreamReader* stream15 = new StreamReader();
    options.addReader(stream15);
    *stream15 << "catin" << "caca" << "catin1" << "caca" << "catin2" << "caca" << "catin3" << "caca" << "catin4" << "caca" << "catin5" << "caca" << "catin6" << "caca" << "catin7" << "caca" << "catin8" << "caca" << "catin9" << "caca" << "catin10" << "caca" << "catin11" << "caca" << "catin12" << "caca" << "catin13" << "caca" << "catin14" << "caca" << "catin15" << "caca" << "catin16" << "caca" << "catin17" << "caca" << "catin18" << "caca" << "catin19" << "caca" << "catin20" << "caca" << "catin21" << "caca" << "catin22" << "caca" << "catin23" << "caca" << "catin24" << "caca" << "catin25" << "caca" << "catin26" << "caca" << "catin27" << "caca" << "catin28" << "caca" << "catin29" << "caca" << "catin30" << "caca" << "catin31" << "caca" << "catin32" << "caca" << "catin33" << "caca" << "catin34" << "caca" << "catin35" << "caca" << "catin36" << "caca" << "catin37" << "caca" << "catin38" << "caca" << "catin39" << "caca" << "catin40" << "caca" << "catin41" << "caca" << "catin42" << "caca" << "catin43" << "caca" << "catin44" << "caca";
    options.addOption("catin", dummy).addOption("catin1", dummy).addOption("catin2", dummy).addOption("catin3", dummy).addOption("catin4", dummy).addOption("catin5", dummy).addOption("catin6", dummy).addOption("catin7", dummy).addOption("catin8", dummy).addOption("catin9", dummy).addOption("catin10", dummy).addOption("catin11", dummy).addOption("catin12", dummy).addOption("catin13", dummy).addOption("catin14", dummy).addOption("catin15", dummy).addOption("catin16", dummy).addOption("catin17", dummy).addOption("catin18", dummy).addOption("catin19", dummy).addOption("catin20", dummy).addOption("catin21", dummy).addOption("catin22", dummy).addOption("catin23", dummy).addOption("catin24", dummy).addOption("catin25", dummy).addOption("catin26", dummy).addOption("catin27", dummy).addOption("catin28", dummy).addOption("catin29", dummy).addOption("catin30", dummy).addOption("catin31", dummy).addOption("catin32", dummy).addOption("catin33", dummy).addOption("catin34", dummy).addOption("catin35", dummy).addOption("catin36", dummy).addOption("catin37", dummy).addOption("catin38", dummy).addOption("catin39", dummy).addOption("catin40", dummy).addOption("catin41", dummy).addOption("catin42", dummy).addOption("catin43", dummy).addOption("catin44", dummy);

    StreamReader* stream16 = new StreamReader();
    options.addReader(stream16);
    *stream16 << "choufleur" << "caca" << "choufleur1" << "caca" << "choufleur2" << "caca" << "choufleur3" << "caca" << "choufleur4" << "caca" << "choufleur5" << "caca" << "choufleur6" << "caca" << "choufleur7" << "caca" << "choufleur8" << "caca" << "choufleur9" << "caca" << "choufleur10" << "caca" << "choufleur11" << "caca" << "choufleur12" << "caca" << "choufleur13" << "caca" << "choufleur14" << "caca" << "choufleur15" << "caca" << "choufleur16" << "caca" << "choufleur17" << "caca" << "choufleur18" << "caca" << "choufleur19" << "caca" << "choufleur20" << "caca" << "choufleur21" << "caca" << "choufleur22" << "caca" << "choufleur23" << "caca" << "choufleur24" << "caca" << "choufleur25" << "caca" << "choufleur26" << "caca" << "choufleur27" << "caca" << "choufleur28" << "caca" << "choufleur29" << "caca" << "choufleur30" << "caca" << "choufleur31" << "caca" << "choufleur32" << "caca" << "choufleur33" << "caca" << "choufleur34" << "caca" << "choufleur35" << "caca" << "choufleur36" << "caca" << "choufleur37" << "caca" << "choufleur38" << "caca" << "choufleur39" << "caca" << "choufleur40" << "caca" << "choufleur41" << "caca" << "choufleur42" << "caca" << "choufleur43" << "caca" << "choufleur44" << "caca";
    options.addOption("choufleur", dummy).addOption("choufleur1", dummy).addOption("choufleur2", dummy).addOption("choufleur3", dummy).addOption("choufleur4", dummy).addOption("choufleur5", dummy).addOption("choufleur6", dummy).addOption("choufleur7", dummy).addOption("choufleur8", dummy).addOption("choufleur9", dummy).addOption("choufleur10", dummy).addOption("choufleur11", dummy).addOption("choufleur12", dummy).addOption("choufleur13", dummy).addOption("choufleur14", dummy).addOption("choufleur15", dummy).addOption("choufleur16", dummy).addOption("choufleur17", dummy).addOption("choufleur18", dummy).addOption("choufleur19", dummy).addOption("choufleur20", dummy).addOption("choufleur21", dummy).addOption("choufleur22", dummy).addOption("choufleur23", dummy).addOption("choufleur24", dummy).addOption("choufleur25", dummy).addOption("choufleur26", dummy).addOption("choufleur27", dummy).addOption("choufleur28", dummy).addOption("choufleur29", dummy).addOption("choufleur30", dummy).addOption("choufleur31", dummy).addOption("choufleur32", dummy).addOption("choufleur33", dummy).addOption("choufleur34", dummy).addOption("choufleur35", dummy).addOption("choufleur36", dummy).addOption("choufleur37", dummy).addOption("choufleur38", dummy).addOption("choufleur39", dummy).addOption("choufleur40", dummy).addOption("choufleur41", dummy).addOption("choufleur42", dummy).addOption("choufleur43", dummy).addOption("choufleur44", dummy);

    StreamReader* stream17 = new StreamReader();
    options.addReader(stream17);
    *stream17 << "chien" << "caca" << "chien1" << "caca" << "chien2" << "caca" << "chien3" << "caca" << "chien4" << "caca" << "chien5" << "caca" << "chien6" << "caca" << "chien7" << "caca" << "chien8" << "caca" << "chien9" << "caca" << "chien10" << "caca" << "chien11" << "caca" << "chien12" << "caca" << "chien13" << "caca" << "chien14" << "caca" << "chien15" << "caca" << "chien16" << "caca" << "chien17" << "caca" << "chien18" << "caca" << "chien19" << "caca" << "chien20" << "caca" << "chien21" << "caca" << "chien22" << "caca" << "chien23" << "caca" << "chien24" << "caca" << "chien25" << "caca" << "chien26" << "caca" << "chien27" << "caca" << "chien28" << "caca" << "chien29" << "caca" << "chien30" << "caca" << "chien31" << "caca" << "chien32" << "caca" << "chien33" << "caca" << "chien34" << "caca" << "chien35" << "caca" << "chien36" << "caca" << "chien37" << "caca" << "chien38" << "caca" << "chien39" << "caca" << "chien40" << "caca" << "chien41" << "caca" << "chien42" << "caca" << "chien43" << "caca" << "chien44" << "caca";
    options.addOption("chien", dummy).addOption("chien1", dummy).addOption("chien2", dummy).addOption("chien3", dummy).addOption("chien4", dummy).addOption("chien5", dummy).addOption("chien6", dummy).addOption("chien7", dummy).addOption("chien8", dummy).addOption("chien9", dummy).addOption("chien10", dummy).addOption("chien11", dummy).addOption("chien12", dummy).addOption("chien13", dummy).addOption("chien14", dummy).addOption("chien15", dummy).addOption("chien16", dummy).addOption("chien17", dummy).addOption("chien18", dummy).addOption("chien19", dummy).addOption("chien20", dummy).addOption("chien21", dummy).addOption("chien22", dummy).addOption("chien23", dummy).addOption("chien24", dummy).addOption("chien25", dummy).addOption("chien26", dummy).addOption("chien27", dummy).addOption("chien28", dummy).addOption("chien29", dummy).addOption("chien30", dummy).addOption("chien31", dummy).addOption("chien32", dummy).addOption("chien33", dummy).addOption("chien34", dummy).addOption("chien35", dummy).addOption("chien36", dummy).addOption("chien37", dummy).addOption("chien38", dummy).addOption("chien39", dummy).addOption("chien40", dummy).addOption("chien41", dummy).addOption("chien42", dummy).addOption("chien43", dummy).addOption("chien44", dummy);


    StreamReader* stream18 = new StreamReader();
    options.addReader(stream18);
    *stream18 << "musique" << "caca" << "musique1" << "caca" << "musique2" << "caca" << "musique3" << "caca" << "musique4" << "caca" << "musique5" << "caca" << "musique6" << "caca" << "musique7" << "caca" << "musique8" << "caca" << "musique9" << "caca" << "musique10" << "caca" << "musique11" << "caca" << "musique12" << "caca" << "musique13" << "caca" << "musique14" << "caca" << "musique15" << "caca" << "musique16" << "caca" << "musique17" << "caca" << "musique18" << "caca" << "musique19" << "caca" << "musique20" << "caca" << "musique21" << "caca" << "musique22" << "caca" << "musique23" << "caca" << "musique24" << "caca" << "musique25" << "caca" << "musique26" << "caca" << "musique27" << "caca" << "musique28" << "caca" << "musique29" << "caca" << "musique30" << "caca" << "musique31" << "caca" << "musique32" << "caca" << "musique33" << "caca" << "musique34" << "caca" << "musique35" << "caca" << "musique36" << "caca" << "musique37" << "caca" << "musique38" << "caca" << "musique39" << "caca" << "musique40" << "caca" << "musique41" << "caca" << "musique42" << "caca" << "musique43" << "caca" << "musique44" << "caca";
    options.addOption("musique", dummy).addOption("musique1", dummy).addOption("musique2", dummy).addOption("musique3", dummy).addOption("musique4", dummy).addOption("musique5", dummy).addOption("musique6", dummy).addOption("musique7", dummy).addOption("musique8", dummy).addOption("musique9", dummy).addOption("musique10", dummy).addOption("musique11", dummy).addOption("musique12", dummy).addOption("musique13", dummy).addOption("musique14", dummy).addOption("musique15", dummy).addOption("musique16", dummy).addOption("musique17", dummy).addOption("musique18", dummy).addOption("musique19", dummy).addOption("musique20", dummy).addOption("musique21", dummy).addOption("musique22", dummy).addOption("musique23", dummy).addOption("musique24", dummy).addOption("musique25", dummy).addOption("musique26", dummy).addOption("musique27", dummy).addOption("musique28", dummy).addOption("musique29", dummy).addOption("musique30", dummy).addOption("musique31", dummy).addOption("musique32", dummy).addOption("musique33", dummy).addOption("musique34", dummy).addOption("musique35", dummy).addOption("musique36", dummy).addOption("musique37", dummy).addOption("musique38", dummy).addOption("musique39", dummy).addOption("musique40", dummy).addOption("musique41", dummy).addOption("musique42", dummy).addOption("musique43", dummy).addOption("musique44", dummy);

	StreamReader* stream19 = new StreamReader();
    options.addReader(stream19);
    *stream19 << "smile" << "caca" << "smile1" << "caca" << "smile2" << "caca" << "smile3" << "caca" << "smile4" << "caca" << "smile5" << "caca" << "smile6" << "caca" << "smile7" << "caca" << "smile8" << "caca" << "smile9" << "caca" << "smile10" << "caca" << "smile11" << "caca" << "smile12" << "caca" << "smile13" << "caca" << "smile14" << "caca" << "smile15" << "caca" << "smile16" << "caca" << "smile17" << "caca" << "smile18" << "caca" << "smile19" << "caca" << "smile20" << "caca" << "smile21" << "caca" << "smile22" << "caca" << "smile23" << "caca" << "smile24" << "caca" << "smile25" << "caca" << "smile26" << "caca" << "smile27" << "caca" << "smile28" << "caca" << "smile29" << "caca" << "smile30" << "caca" << "smile31" << "caca" << "smile32" << "caca" << "smile33" << "caca" << "smile34" << "caca" << "smile35" << "caca" << "smile36" << "caca" << "smile37" << "caca" << "smile38" << "caca" << "smile39" << "caca" << "smile40" << "caca" << "smile41" << "caca" << "smile42" << "caca" << "smile43" << "caca" << "smile44" << "caca";
    options.addOption("smile", dummy).addOption("smile1", dummy).addOption("smile2", dummy).addOption("smile3", dummy).addOption("smile4", dummy).addOption("smile5", dummy).addOption("smile6", dummy).addOption("smile7", dummy).addOption("smile8", dummy).addOption("smile9", dummy).addOption("smile10", dummy).addOption("smile11", dummy).addOption("smile12", dummy).addOption("smile13", dummy).addOption("smile14", dummy).addOption("smile15", dummy).addOption("smile16", dummy).addOption("smile17", dummy).addOption("smile18", dummy).addOption("smile19", dummy).addOption("smile20", dummy).addOption("smile21", dummy).addOption("smile22", dummy).addOption("smile23", dummy).addOption("smile24", dummy).addOption("smile25", dummy).addOption("smile26", dummy).addOption("smile27", dummy).addOption("smile28", dummy).addOption("smile29", dummy).addOption("smile30", dummy).addOption("smile31", dummy).addOption("smile32", dummy).addOption("smile33", dummy).addOption("smile34", dummy).addOption("smile35", dummy).addOption("smile36", dummy).addOption("smile37", dummy).addOption("smile38", dummy).addOption("smile39", dummy).addOption("smile40", dummy).addOption("smile41", dummy).addOption("smile42", dummy).addOption("smile43", dummy).addOption("smile44", dummy);

	StreamReader* stream20 = new StreamReader();
    options.addReader(stream20);
    *stream20 << "love" << "caca" << "love1" << "caca" << "love2" << "caca" << "love3" << "caca" << "love4" << "caca" << "love5" << "caca" << "love6" << "caca" << "love7" << "caca" << "love8" << "caca" << "love9" << "caca" << "love10" << "caca" << "love11" << "caca" << "love12" << "caca" << "love13" << "caca" << "love14" << "caca" << "love15" << "caca" << "love16" << "caca" << "love17" << "caca" << "love18" << "caca" << "love19" << "caca" << "love20" << "caca" << "love21" << "caca" << "love22" << "caca" << "love23" << "caca" << "love24" << "caca" << "love25" << "caca" << "love26" << "caca" << "love27" << "caca" << "love28" << "caca" << "love29" << "caca" << "love30" << "caca" << "love31" << "caca" << "love32" << "caca" << "love33" << "caca" << "love34" << "caca" << "love35" << "caca" << "love36" << "caca" << "love37" << "caca" << "love38" << "caca" << "love39" << "caca" << "love40" << "caca" << "love41" << "caca" << "love42" << "caca" << "love43" << "caca" << "love44" << "caca";
    options.addOption("love", dummy).addOption("love1", dummy).addOption("love2", dummy).addOption("love3", dummy).addOption("love4", dummy).addOption("love5", dummy).addOption("love6", dummy).addOption("love7", dummy).addOption("love8", dummy).addOption("love9", dummy).addOption("love10", dummy).addOption("love11", dummy).addOption("love12", dummy).addOption("love13", dummy).addOption("love14", dummy).addOption("love15", dummy).addOption("love16", dummy).addOption("love17", dummy).addOption("love18", dummy).addOption("love19", dummy).addOption("love20", dummy).addOption("love21", dummy).addOption("love22", dummy).addOption("love23", dummy).addOption("love24", dummy).addOption("love25", dummy).addOption("love26", dummy).addOption("love27", dummy).addOption("love28", dummy).addOption("love29", dummy).addOption("love30", dummy).addOption("love31", dummy).addOption("love32", dummy).addOption("love33", dummy).addOption("love34", dummy).addOption("love35", dummy).addOption("love36", dummy).addOption("love37", dummy).addOption("love38", dummy).addOption("love39", dummy).addOption("love40", dummy).addOption("love41", dummy).addOption("love42", dummy).addOption("love43", dummy).addOption("love4", dummy);

    int c1 = clock();
    options.readOptions();
    int c2 = clock();

    std::cout << "clocks : " << c2 - c1 << "\n";
    return 0;
}



